# in a line of a makefile starts a comment.
# Blank lines are also ignored

# say_hello behaves like a function name but is called a target
# The prerequisites or dependencies follow the target.
# The command echo "Hello World" is called the recipe. 
# The recipe uses prerequisites to make a target. 
# The target, prerequisites, and recipes together make a rule.
# The format is:\

target: prerequisites\
<TAB> recipe

say_hello:
	echo "Hello World"